### PR TITLE
Use SQLAlchemy to escape SQL query

### LINKED ISSUE #19: Convert load.py to use SQLAlchemy
Please revise the prototype's [load.py](https://github.com/jamesaoverton/cmi-pb-terminology/blob/next/src/script/load.py) to use `bindparam` and `sql_text` from `sqlalchemy.sql.expression` as done in [sprocket run.py](https://github.com/ontodev/sprocket/blob/main/sprocket/run.py).

I would like to output properly escaped SQL strings at this point -- I don't want to execute the SQL from Python yet.

### PR DESCRIPTION
**Pull request by beckyjackson**
Resolves #19

### CODE REVIEW

**Comment by beckyjackson** [comment]
@jamesaoverton do the comments (description) need to be escaped? SQLAlchemy is adding quotes around some of them.

**Comment by jamesaoverton** [comment]
I can see how the comments would cause problems. We can omit them.

**Comment by beckyjackson** [comment]
Omit the comments from the escaping, or omit them entirely from the output?

**Comment by jamesaoverton** [comment]
I'm fine with omitting the comments entirely from the generated SQL.

**Comment by jamesaoverton** [comment]
You showed me the general approach, and I made a couple more changes. Thanks!

**Pull request merged**
